name: "🐛 Bug Report"
description: "Report a bug or unexpected behavior"
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: "Describe the Bug"
      description: "Clear and concise description of what's happening"
      placeholder: "When I tap the button, the app crashes..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "How to reproduce the issue"
      placeholder: |
        1. Open the app
        2. Navigate to...
        3. Tap on...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should happen instead"
      placeholder: "The app should..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Error Logs"
      description: "Relevant error messages or stack traces"
      render: "shell"

  - type: input
    id: version
    attributes:
      label: "App Version"
      placeholder: "1.2.0"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
      placeholder: "Android 13 / iOS 17"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: "Device Model"
      placeholder: "Samsung Galaxy S23 / iPhone 15"

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Any other relevant information"

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I've searched for similar issues"
          required: true
        - label: "This is not a duplicate"
          required: true
        - label: "I'm using the latest version"
          required: false
