name: "✨ Feature Request"
description: "Suggest a new feature or improvement"
labels: ["enhancement", "feature-request"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide clear details about what you'd like to see.

  - type: textarea
    id: feature
    attributes:
      label: "Feature Description"
      description: "Clear and detailed description of the proposed feature"
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "Use Case"
      description: "Why is this feature needed? What problem does it solve?"
      placeholder: "This would help because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "How should this feature work?"
      placeholder: "The feature could work like..."

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternative Solutions"
      description: "Are there other ways to accomplish this?"

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Any other relevant information, screenshots, mockups, etc."

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I've searched for similar features"
          required: true
        - label: "This is not a duplicate"
          required: true
